

INSERT_ORDER = 0
CANCELED_ORDER = 1
RESET_SHARES = 2
CHANGE_START_CASH = 3
ADJUST_STATE = 4
ORDER_STATE_CHANGE = 5
ADJUST_TO = 6
STRATEGY_START = 7
STOP_STRATEGY = 8
START_STRATEGY = 9
RESTART_STRATEGY = 10

